### ISSUE TITLE
cannot use ngx-store

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#177]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
1. Install https://github.com/zoomsphere/ngx-store
2. run `npm run build:universal prod`
3. run `npm run serve`

Error:
ReferenceError: localStorage is not defined
    at Object.<anonymous> (/Users/personal/code/udoma/webapp/.server/server.js:1:2943050)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.module.exports.list (/Users/personal/code/udoma/webapp/.server/server.js:1:553740)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.<anonymous> (/Users/personal/code/udoma/webapp/.server/server.js:1:779544)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.<anonymous> (/Users/personal/code/udoma/webapp/.server/server.js:1:623706)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.<anonymous> (/Users/personal/code/udoma/webapp/.server/server.js:1:778813)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)

**Expected/desired behavior**
Run smoothly 

**QUESTION:**
How I can define it only for the browser. Can I create second custom decorator which is checking the platform?

**Comment by vlados** [comment]
Probably it was a problem with the module. I switched to https://github.com/PillowPillow/ng2-webstorage and it works perfectly for now
