### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#229]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```
After running npm run build:universal-prod && npm run serve I get this error:
```
(function (exports, require, module, __filename, __dirname) { (function(modules){function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}var installedModules={};__webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.defineProperty(exports,name,{configurable:!1,enumerable:!0,get:getter})},__webpack_require__.n=function(module){var getter=module&&module.__esModule?function(){return module.default}:function(){return module};return __webpack_require__.d(getter,"a",getter),getter},__webpack_require__.o=function(object,property){return Object.prototype.hasOwnProperty.call(object,property)},__webpack_require__.p="/assets

ReferenceError: window is not defined
    at /Users/personal/code/udoma/webapp/.server/server.js:1:427049
    at freeze (/Users/personal/code/udoma/webapp/.server/server.js:1:404783)
    at Object.<anonymous> (/Users/personal/code/udoma/webapp/.server/server.js:1:404801)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.__extends.__extends.Object.setPrototypeOf.__proto__ (/Users/personal/code/udoma/webapp/.server/server.js:1:2758455)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.L.MarkerClusterGroup.L.FeatureGroup.extend.options.maxClusterRadius (/Users/personal/code/udoma/webapp/.server/server.js:1:3961671)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
    at Object.__extends.__extends.Object.setPrototypeOf.__proto__ (/Users/personal/code/udoma/webapp/.server/server.js:1:2757032)
    at __webpack_require__ (/Users/personal/code/udoma/webapp/.server/server.js:1:285)
```
**How I can debug it and find the module causing the error?**

**Comment by fulls1z3** [comment]
Explained on #227.
