### ISSUE TITLE
universal production build failing on ubuntu with exit code 137

### ISSUE THREAD

**Issue by sagarguhe** [fulls1z3/universal#233]
**I'm submitting a ...**
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
I am trying to `build:universal-prod` on my linode Ubuntu 16.04 64 bit system but this is failing to build. I tried to `build:universal-dev` and this worked perfectly but not the `prod` version. On my local (Fedora 25, node: 8.4.0, npm: 5.5.1) I am not experiencing this behavior. Below is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:universal-prod' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild:universal-prod',
4 verbose run-script   'build:universal-prod',
4 verbose run-script   'postbuild:universal-prod' ]
5 info lifecycle @ng-seed/universal@1.3.0~prebuild:universal-prod: @ng-seed/universal@1.3.0
6 info lifecycle @ng-seed/universal@1.3.0~build:universal-prod: @ng-seed/universal@1.3.0
7 verbose lifecycle @ng-seed/universal@1.3.0~build:universal-prod: unsafe-perm in lifecycle true
8 verbose lifecycle @ng-seed/universal@1.3.0~build:universal-prod: PATH: /root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/bin/node-gyp-bin:/var/www/hirely.me/node_modules/.bin:/root/.nvm/versions/node/v8.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle @ng-seed/universal@1.3.0~build:universal-prod: CWD: /var/www/hirely.me
10 silly lifecycle @ng-seed/universal@1.3.0~build:universal-prod: Args: [ '-c',
10 silly lifecycle   'npm run clean:artifacts && gulp build:universal-prod --color' ]
11 silly lifecycle @ng-seed/universal@1.3.0~build:universal-prod: Returned: code: 137  signal: null
12 info lifecycle @ng-seed/universal@1.3.0~build:universal-prod: Failed to exec build:universal-prod script
13 verbose stack Error: @ng-seed/universal@1.3.0 build:universal-prod: `npm run clean:artifacts && gulp build:universal-prod --color`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @ng-seed/universal@1.3.0
15 verbose cwd /var/www/hirely.me
16 verbose Linux 4.9.50-x86_64-linode86
17 verbose argv "/root/.nvm/versions/node/v8.9.1/bin/node" "/root/.nvm/versions/node/v8.9.1/bin/npm" "run" "build:universal-prod"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 137
22 error @ng-seed/universal@1.3.0 build:universal-prod: `npm run clean:artifacts && gulp build:universal-prod --color`
22 error Exit status 137
23 error Failed at the @ng-seed/universal@1.3.0 build:universal-prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**
`git clone https://github.com/ng-seed/universal.git`
`cd universal`
`yarn`
`npm run build:universal-prod`

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** 4.4.6

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 8.9.1 (npm 5.5.1)
- Platform:  Linux

* Others:

**Comment by sagarguhe** [comment]
Ok, I think it should be memory issue which is caused by gulp. My server has 1Gb of Ram but this is not sufficient.

**Comment by sagarguhe** [comment]
I build the build on my local and uploaded build files to the server...

**Comment by fulls1z3** [comment]
@sagarguhe it's very likely to be a memory issue, and honestly 1 GB is too low for such a build operation.
