### ISSUE TITLE
copy:index.html issue while running `npm run build:spa-dev`

### ISSUE THREAD

**Issue by deefactorial** [fulls1z3/universal#279]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

running `npm run build:spa-dev` fails on copy:index.html gulp command:
```
[10:36:01] Starting 'copy:index.html'...
[10:36:01] 'copy:index.html' errored after 20 ms
[10:36:01] Error: Invalid dest() folder argument. Please specify a non-empty string or a function.
    at Gulp.dest (/Users/shawnan/CRUD/node_modules/vinyl-fs/lib/dest/index.js:21:11)
    at /Users/shawnan/CRUD/tools/build/gulp-helpers.js:56:36
    at /Users/shawnan/CRUD/node_modules/lazypipe/index.js:27:19
    at Array.map (native)
    at build (/Users/shawnan/CRUD/node_modules/lazypipe/index.js:26:37)
    at Object.exports.debug (/Users/shawnan/CRUD/tools/build/gulp-helpers.js:57:7)
    at copy (/Users/shawnan/CRUD/tools/build/gulp-tasks.js:90:18)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/Users/shawnan/CRUD/node_modules/async-done/index.js:39:18)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
[10:36:01] 'build:spa-dev' errored after 1.26 s
```

**Expected/desired behavior**

I expected the command to finish without errors

**Minimal reproduction of the problem with instructions**

```sh
yarn
npm run build:spa-dev
```

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 8.0.0  
- NPM version: 5.0.0
- Platform:  Mac

* Others:

`npm ls` output attached
[-.txt](https://github.com/ng-seed/universal/files/1616298/-.txt)

**Comment by fulls1z3** [comment]
@deefactorial I had a look at the npm output, but honestly it didn't help much.

Did you just clone the repo on made the initial build, or you pulled the latest on your project?

FYI, I've got exactly the same node and npm versions on Windows 10, and made a fresh repo clone - and it ran successfully. However, I don't believe the fact that *it runs on my machine*, and any further info is always welcome 👍

**Comment by deefactorial** [comment]
@fulls1z3 It appears to have been a package installation issue, I think when I ran `npm install` instead of `yarn` it caused an issue with the installed packages, destroying the repository and starting again from scratch resolved the issue.

Thanks for looking into it.

**Comment by vlados** [comment]
I can confirm: 
If you installed the packages with `npm install` simply run `yarn` and it will work after that
