### ISSUE TITLE
ngx-i18n-router doesn't work

### ISSUE THREAD

**Issue by hillbrm** [fulls1z3/universal#283]
Hello!
In last version of project I uncommented i18n-router in all files where found it and get errors at console.

**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
```
git pull repo
npm install
uncomment all lines for i18n-router
npm run build:universal-dev
wait to build it and exit
run it again
```

Hit an errors:

```
Error: [at-loader] ./src/client/app/framework/core/core.module.ts:44:69 
    TS2304: Cannot find name 'routes'.

Error: [at-loader] ./src/client/app/framework/core/core.module.ts:45:57 
    TS2559: Type '"routes"' has no properties in common with type 'I18NRouterSettings'.

Error: [at-loader] ./src/client/app/framework/i18n/src/i18n.service.ts:55:30 
    TS2339: Property 'useLanguage' does not exist on type 'I18NRouterService'.

Error: [at-loader] ./src/client/app/framework/i18n/src/i18n.service.ts:72:9 
    TS2451: Cannot redeclare block-scoped variable 'detectedLanguage'.

Error: [at-loader] ./src/client/app/framework/i18n/src/i18n.service.ts:78:5 
    TS1156: 'const' declarations can only be declared inside a block.

Error: [at-loader] ./src/client/app/framework/i18n/src/i18n.service.ts:78:11 
    TS2451: Cannot redeclare block-scoped variable 'detectedLanguage'.

    (6) error(s) total.


[23:11:25] Starting 'bundle:universal-server-dev'...
Error: TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/packages/compiler/esm5/src/aot/lazy_routes.js:65:6)
    at listLazyRoutes (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/packages/compiler/esm5/src/aot/lazy_routes.js:40:10)
    at visitLazyRoute (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/packages/compiler/esm5/src/aot/compiler.js:775:14)
    at visitLazyRoute (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/packages/compiler/esm5/src/aot/compiler.js:779:12)
    at AotCompiler.listLazyRoutes (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/packages/compiler/esm5/src/aot/compiler.js:743:17)
    at AngularCompilerProgram.listLazyRoutes (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/packages/compiler-cli/src/transformers/program.ts:196:26)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/packages/compiler-cli/src/ngtools_api.ts:95:34)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/Users/m.ilichev/Documents/newallcoin/angular/universal-master-4/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:562:50)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

    (1) error(s) total.
```

**Environment**
Angular 5
Node version: v8.9.4
Platform: macOS 10.13.2
Webpack: 3.10
Typescript: 2.6.2
NPM: 5.6.0

**Comment by fulls1z3** [comment]
@hillbrm for a while, it should stay commented - there's an issue we need to solve with `@ngtools/webpack` (*more specifically with `@angular/complier-cli`*).

You can find detailed info on this issue: https://github.com/fulls1z3/ngx-i18n-router/issues/2

**Comment by hillbrm** [comment]
Thanx, but i cant find ngtools_impl file.. Latest angular-cli does not have this file?
