### ISSUE TITLE
static injector error when serving universal-prod

### ISSUE THREAD

**Issue by bobsingor** [fulls1z3/universal#284]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
When I follow the documentation and run:
```
npm run build:universal-prod
npm run serve
```
and in the browser go to: 
```
http://localhost:8000
```
I get the following error : 
```
Express server listening on http://localhost:8000
TypeError: StaticInjectorError(AppServerModule)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
    Right-hand side of 'instanceof' is not an object
    at insertElement (/Users/bobsingor/Github/universal-original/.server/server.js:1:1931338)
    at insertHTMLElement (/Users/bobsingor/Github/universal-original/.server/server.js:1:1931060)
    at before_head_mode (/Users/bobsingor/Github/universal-original/.server/server.js:1:1969190)
    at HTMLParser.htmlparser.insertToken (/Users/bobsingor/Github/universal-original/.server/server.js:1:1930092)
    at /Users/bobsingor/Github/universal-original/.server/server.js:1:1935200
    at data_state (/Users/bobsingor/Github/universal-original/.server/server.js:1:1935238)
    at scanChars (/Users/bobsingor/Github/universal-original/.server/server.js:1:1926850)
    at Object.parse (/Users/bobsingor/Github/universal-original/.server/server.js:1:1925007)
    at Object.exports.createDocument (/Users/bobsingor/Github/universal-original/.server/server.js:1:3724599)
    at Object.exports.createWindow (/Users/bobsingor/Github/universal-original/.server/server.js:1:3724755)
TypeError: StaticInjectorError(AppServerModule)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
    Right-hand side of 'instanceof' is not an object
    at insertElement (/Users/bobsingor/Github/universal-original/.server/server.js:1:1931338)
    at insertHTMLElement (/Users/bobsingor/Github/universal-original/.server/server.js:1:1931060)
    at before_head_mode (/Users/bobsingor/Github/universal-original/.server/server.js:1:1969190)
    at HTMLParser.htmlparser.insertToken (/Users/bobsingor/Github/universal-original/.server/server.js:1:1930092)
    at /Users/bobsingor/Github/universal-original/.server/server.js:1:1935200
    at data_state (/Users/bobsingor/Github/universal-original/.server/server.js:1:1935238)
    at scanChars (/Users/bobsingor/Github/universal-original/.server/server.js:1:1926850)
    at Object.parse (/Users/bobsingor/Github/universal-original/.server/server.js:1:1925007)
    at Object.exports.createDocument (/Users/bobsingor/Github/universal-original/.server/server.js:1:3724599)
    at Object.exports.createWindow (/Users/bobsingor/Github/universal-original/.server/server.js:1:3724755)
```

* **For Tooling issues:**
- Node version: v8.9.1
- Platform:  Mac

**Comment by bobsingor** [comment]
By removing uglify I don't get this error anymore

**Comment by fulls1z3** [comment]
@bobsingor i watched this movie earlier :)

Either you’re using a package with `ApplicationRef` dependency, or you should have manually turned on uglification.

Try commenting the `ConfigMergeLoader` and switch to `ConfigStaticLoader` (*by copying the values from `assets/config.local.json` to its constructor*) and let’s see if it happens or not.

In my case it was the interference with TransferHttpCacheModule and ConfigHttpLoader.

**Comment by andrey-programmist** [comment]
I have the same issue. Commenting `ConfigLoader` didn't help.

**Comment by ghost** [comment]
I can build successfully after remove prodconfig() in webpack.config.js

**Comment by andrey-programmist** [comment]
> I can build successfully after remove prodconfig() in webpack.config.js

I can build with such config successfully
```
const stageConfig = function () {
  return {
    plugins: [
      new uglifyJsPlugin({
        uglifyOptions: {
          compress: false,
          mangle: false,
          comments: false
        }
      })
    ]
  };
}
```

**Comment by vlados** [comment]
I can confirm fix in webpack.config.ts
```
const prodConfig = function (mangle = true) {
    return {
        /**
         * Add additional plugins to the compiler.
         *
         * See: http://webpack.github.io/docs/configuration.html#plugins
         */
        plugins: [
            /**
             * Plugin: UglifyJsPlugin
             * Description: Minimize all JavaScript output of chunks.
             * Loaders are switched into minimizing mode.
             *
             * See: https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
             */
            new uglifyJsPlugin({
                uglifyOptions: {
                    ecma: 6,
                    compress: false,
                    mangle: mangle,
                    comments: false

                }
            })
        ]
    };
};
```

**Comment by AnthonyNahas** [comment]
@vlados that worked for me ;)

**Comment by fulls1z3** [comment]
@bobsingor @andrey-programmist @sanyagolub @vlados @AnthonyNahas this issue has been fixed 👍
