### ISSUE TITLE
unreachable endpoint

### ISSUE THREAD

**Issue by vlados** [fulls1z3/universal#484]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

1. Git clone
2. npm install
3. Error
```
[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./.server/server.js`
Express server listening on http://localhost:8000
(node:95472) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR Endpoint unreachable!
ERROR { Error: Uncaught (in promise): Endpoint unreachable!
    at resolvePromise (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:20347)
    at resolvePromise (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:19337)
    at /Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:21881
    at ZoneDelegate.invokeTask (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:11453)
    at Object.onInvokeTask (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:293:2368)
    at ZoneDelegate.invokeTask (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:11343)
    at Zone.runTask (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:4079)
    at drainMicroTaskQueue (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:15045)
    at ZoneTask.invokeTask (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:13094)
    at ZoneTask.invoke (/Users/vlado/code/udoma.bg/universal-clean/.server/server.js:2475:12860)
  rejection: 'Endpoint unreachable!',
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: 'Endpoint unreachable!' },
  zone:
   Zone {
```

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** X.Y.Z

* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 9, tried and with 8 without luck  
- Platform:  osx

* Others:

**Comment by mappedinn** [comment]
the file `./.server/server.js` does not exist.

What I have done is just avoiding it. :(

**Comment by vlados** [comment]
try npm run build:universal-prod

**Comment by fulls1z3** [comment]
@vlados @mappedinn still facing an issue with that?
