### ISSUE TITLE
warning: ./node_modules/express/lib/view.js

### ISSUE THREAD

**Issue by kkaabbaa** [fulls1z3/universal#57]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

I did not change anything in the code, just clone your version
When I try to run `$npm run build:universal-dev`
I have error:

```
21:12:36] Finished 'bundle:universal-browser-dev' after 21 s
[21:12:36] Starting 'bundle:universal-server-dev'...
Warning: ./node_modules/express/lib/view.js
79:29-41 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/Compilation.js:694:24)
    at Compilation.finish (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/Compilation.js:552:9)
    at applyPluginsParallel.err (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/Compilation.js:498:11)
    at processModuleDependencies.err (/Users/kkaabbaa/projects/johndeverall/test-universal/universal/node_modules/webpack/lib/Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

    (1) warning(s) total.

Webpack: output server.0.chunk.js
```

**Please tell us about your environment:**

macOS Sierra

* **Node (for AoT issues):** `node --version` =   v6.11.1

**Comment by PTC-JoshuaMatthews** [comment]
+1

**Comment by zmnv** [comment]
Same ...

```
[00:28:45] Finished 'bundle:universal-browser-prod' after 1.52 min
[00:28:45] Starting 'bundle:universal-server-prod'...
Warning: ./node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings 
```

**Comment by JohnPhilipPearson** [comment]
I thought I would help with environment and steps as I have the same warning.

Mac OS version => 10.13.1 
node -v => v8.9.1
npm -v => 5.5.1

steps taken
git pulled on 20171130 with zero changes to the seed
rm -rf node_modules
npm install, error on node-sass
npm rebuild node-sass --force
npm install
npm run clean:artifacts
npm run build:universal-dev

Warning: ./node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/.../universal/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/.../universal/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/.../universal/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/.../universal/node_modules/webpack/lib/Compiler.js:506:17)
    at /.../universal/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/.../universal/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/.../universal/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 @ ./node_modules/express/lib/view.js
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./src/server/server.ts

    (1) warning(s) total.

**Comment by fulls1z3** [comment]
@kkaabbaa @PTC-JoshuaMatthews @zmnv @JohnPhilipPearson all done with webpack 4, enjoy the latest stack 👍
