### ISSUE TITLE
ngx-cache errors

### ISSUE THREAD

**Issue by gedgud** [fulls1z3/universal#8]
Hi, when I try install npm packages I get these errors:
```
npm ERR! notarget No compatible version found: @ngx-cache/core@0.0.1-alpha.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.0-beta.1
```

In package.json file change some version and all packages installed.
```
"@ngx-cache/core": "0.4.0-beta.1",
"@ngx-cache/platform-browser": "0.4.0-beta.1",
"@ngx-cache/platform-server": "0.4.0-beta.1",
```
But when I try to start app with **npm run serve** I have new errors:
```
Error: Invalid provider for InjectionToken CACHE. useClass cannot be undefined.
           Usually it happens when:
           1. There's a circular dependency (might be caused by using index.ts (barrel) files).
           2. Class was used before it was declared. Use forwardRef in this case.
    at Error (native)
    at syntaxError (C:\Projects2\universal-example-app\.server\server.js:81754:34) [<root>]
    at CompileMetadataResolver._validateProvider (C:\Projects2\universal-example-app\.server\server.js:95116:31) [<root>]
    at C:\Projects2\universal-example-app\.server\server.js:95073:27 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver._getProvidersMetadata (C:\Projects2\universal-example-app\.server\server.js:95065:19) [<root>]
    at C:\Projects2\universal-example-app\.server\server.js:94640:63 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (C:\Projects2\universal-example-app\.server\server.js:94631:49) [<root>]
    at JitCompiler._loadModules (C:\Projects2\universal-example-app\.server\server.js:105812:64) [<root>]
    at JitCompiler._compileModuleAndComponents (C:\Projects2\universal-example-app\.server\server.js:105771:52) [<root>]
    at JitCompiler.compileModuleAsync (C:\Projects2\universal-example-app\.server\server.js:105733:21) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (C:\Projects2\universal-example-app\.server\server.js:5508:25) [<root>]
    at PlatformRef_.bootstrapModule (C:\Projects2\universal-example-app\.server\server.js:5494:21) [<root>]
```

**Comment by fulls1z3** [comment]
Hi, they were awaiting the update I've recently committed. When you pull the latest version from repo, all should work without a problem.
